### ISSUE TITLE
Prevent to join new links when $state.event is prevented

### ISSUE THREAD

**Issue by antoescu** [manuelmazzuola/angular-ui-router-styles#13]
In my case I wanted to prevent adding the css link tag when I had to prevent moving to the next state (due to authentication). I don't know how to do pull requests (sorry, pretty much new to helping the community here), but this is what I did. You can just add this feature, ignore it or whatever you wish. Thanks!

            $rootScope.$on('$stateChangeStart', function (evt, toState) {
              if (!evt.defaultPrevented) { // Added this line
              // From current state to the root
              scope.routeStyles = [];
              for(var state = toState; state && state.name !== ''; state=$$parentState(state)) {
                if(state && state.data && state.data.css) {
                  if(!Array.isArray(state.data.css)) {
                    state.data.css = [state.data.css];
                  }
                  angular.forEach(state.data.css, function(css) {
                    if(scope.routeStyles.indexOf(css) === -1) {
                      scope.routeStyles.push(css);
                    }
                  });
                }
              }
              scope.routeStyles.reverse();
            }
          });

**Comment by manuelmazzuola** [comment]
But the current version listens for the `$stateChangeSuccess` event and not the `$stateChangeStart ` event. So if you do `evt.prevendDefault()` in your `$stateChangeStart` callback, the `$stateChangeSuccess` callback of this plugin is not triggered.

**Comment by antoescu** [comment]
I have in my bower "angular-ui-router-styles": "~0.0.5", because it seems I cannot upload it more since you don't have new releases, although you have 10 commits more from the last release. Should I wait for new releases? Can I put in my bower no releases versions? if so, how? Thanks!

**Comment by manuelmazzuola** [comment]
I've just made a new release, 0.0.6.
Try it and let me know :+1:

**Comment by antoescu** [comment]
Yes, perfect! Thanks! You can close this ;)
