### ISSUE TITLE
Release on npm aswell

### ISSUE THREAD

**Issue by walliski** [manuelmazzuola/angular-ui-router-styles#15]
Hi

Going to bother you again. After having problems with the dependencies I noticed that a lot of people are using npm instead of Bower for managing client side packages. Most of the packages that I am using in my project are available from npm, but not this one. Could it be possible to have this published in npm also, I am not aware of how much work it is.

Thanks,
Walliski

**Comment by walliski** [comment]
Any comments on this?

**Comment by manuelmazzuola** [comment]
I'm on holiday far away, next week I'll come back and I'll do it, thanks!

Il giorno ven 7 ago 2015 13:51 walliski <notifications@github.com> ha
scritto:

**Comment by walliski** [comment]
:+1:

**Comment by walliski** [comment]
Thanks!

Suppose you could also add dependencies in the npm package?
