### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by renannprado** [manuelmazzuola/angular-ui-router-styles#17]
I've tried below code with angular 1.4.9 and it doesn't work. It is only loading the HTML without the CSS.

```
$urlRouterProvider.otherwise("/login");

$stateProvider
    .state("login", {
        url: "/login",
        controller: "LoginCtrl",
        templateUrl: "views/login/login.html",
        data: {
            css: "views/login/login.css"
        }
    })
```

**Comment by manuelmazzuola** [comment]
Here the plunkr with angular 1.4.9
http://plnkr.co/edit/rJEdureVMHShO08kJE4N?p=preview

I've changed the directive name and modified the usage, I'll update the documentation and release version 1.0.0

**Comment by renannprado** [comment]
Thanks a lot!
I'll test again and update.
Btw another that is a nice to have: provide minified version of the lib

**Comment by renannprado** [comment]
So far so good!
Thanks again :)
