### ISSUE TITLE
isn't working when using views attribute

### ISSUE THREAD

**Issue by Nickkun** [manuelmazzuola/angular-ui-router-styles#20]
I'll try to this solution, but isn't working .. 
for example, 

app.js 
```javascript
...
config(function($httpProvider, $stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise('/');
  $stateProvider.state('index', {
    url: '/',
    views: {
      content: {
        controller: 'LoginCtrl',
        templateUrl: '../views/etc/login.html'
      }
    }
  }).state('list', {
    url: '/list',
    abstract: 'list.main',
    data: {
      css: '../styles/list.css'
    },
    views: {
      content: {
        controller: 'listCtrl',
        templateUrl: '../views/list/list.html'
      }
    }
  })
```
index.html 
```html
<body ng-app="App" ui-router-styles>
```
file hierarchy
─ controller 
└ app.js
─ styles
└ cocolist.css
─ index.html 

please, some advises. thanks.

**Comment by manuelmazzuola** [comment]
Hi!
I've written a plunkr with nested and multiple views and it works fine.

http://plnkr.co/edit/G4v8Ksbis8zLZ1jCxnSZ?p=preview

**Comment by Nickkun** [comment]
Thanks for reply.
i was trying to you plunkr codes but it is not a working yet. 
Would it matter if I was using [`ui.router.default`](https://www.npmjs.com/package/angular-ui-router-default) ?

**Comment by Nickkun** [comment]
problem solved.
the point is ng-app positions.

i was bind "ng-app" property is <body> tag
clearly worked then moved <html> tag 

thannks
