### ISSUE TITLE
duplication in routeStyles array when child state do not define data attribute

### ISSUE THREAD

**Issue by YansongZang** [manuelmazzuola/angular-ui-router-styles#3]
Since child state will inherit parent state's data attribute, any css link in a parent state will be added again by its child state. The issue could be serious if the state tree is deep.

Say, state1 has data: {css: 'state1.css'}, both state1.state12 and state1.state12.state.123 do not define the data attribute. When go to state1.state12, the state1.css will be injected twice. As you can see when go to state1.state12.state123, the state1.css will be injected 3 times!

So I suggest remove duplication after the scope.routeStyles is populated.

Another minor issue, when people add a stylesheet in a child state, in most case we want to override the style in parent stylesheet if the selector overlaps.

Say, state1 has data: {css: 'state1.css'} and state1.state12 has data: {css: 'state12.css'}.

/* state1.css */
...
.container {
    color: blue;
}
...

/* state12.css */
...
.container {
    color: red;
}
...

Since the routeStyles array is constructed in an order from current state to the root, state1.css will be injected after state12.css. Which makes parent's style take higher priority.

Suggest reverse the routeStyles array in the end.

**Comment by manuelmazzuola** [comment]
Thank you !

**Comment by YansongZang** [comment]
My pleasure! Do you have a plan of tagging a new release with my change? So that I don't need to patch my diff every time after I reinstall your package. :)

Thank you.

**Comment by manuelmazzuola** [comment]
Done

!['!!!'](http://i.imgur.com/lGUPnuX.gif)

**Comment by YansongZang** [comment]
Thank you :)
