### ISSUE TITLE
Current state momentarily loses CSS styling when transitioning to a different state

### ISSUE THREAD

**Issue by erikwestra** [manuelmazzuola/angular-ui-router-styles#7]
I'm working on an Ionic application that makes use of angular-ui-router-styles.  One of the complaints I've received from user testing is that my app does a lot of "flickering" as the user moves from one state to another.  Much of this seems to be related to the use of angular-ui-router-styles -- as you transition from one state to another, the existing CSS styling is removed from the current state, and the app then loads the new state and transitions to it.  As a result, the existing state's HTML is displayed for a fraction of a second without any CSS styling applied to it, before being replaced by the new state.

This is made worse if the state being transitioned to uses `resolve` in it's call to `$stateProvider.state()` to download data before the state's contents are displayed -- this introduces a delay in the state transition which makes the removal of the CSS formatting from the previous state all-too obvious to the user.

For example, here is a sample screen image from the app I'm developing:

![image_1](https://cloud.githubusercontent.com/assets/515597/6654397/abed0ff2-cb26-11e4-92f1-11b50e77bb3c.png)

(sorry about the crap contents -- as you can guess, this is a messaging app, and these are just dummy messages entered for testing).  This image shows the state's contents correctly formatted using the CSS file selected using angular-ui-router-styles.  However, if I then click on the "Back" button to go to the parent state, and that parent state takes, say, a second to download the data it needs from the server using `resolve`, then the instant I click on the "Back" button the existing CSS styling is removed and the state's contents suddenly look like this:

![image_2](https://cloud.githubusercontent.com/assets/515597/6654404/03cebf68-cb27-11e4-8faf-6579309047f5.png)

Even without a `resolve` in the destination state, you can still see the CSS styling being removed for a fraction of a second before the new state is displayed, which is what causes my users to complain of "flickering" in my app.

Am I using angular-ui-router-styles incorrectly, perhaps, or is there some way of avoiding this behaviour during state transition?  I tried changing the `rootScope.$on('$stateChangeStart', ...)` call to use `$stateChangeSuccess` instead (and also `$viewContentLoading`), but there's still a noticeable flicker as the existing CSS styling is removed a moment before the new state's contents are displayed.

Any ideas?

Thanks,

 \- Erik.

**Comment by manuelmazzuola** [comment]
Hi, thanks for the report. Is this the `flickering` ? http://plnkr.co/edit/Tngy101W14g3CUoJhOqX?p=preview

**Comment by erikwestra** [comment]
Interesting -- the problem is indeed showing up with your example, but it's not as bad as it appears in my app.  Maybe the performance is better in a desktop browser?  Anyway, yes, this plunker is showing the problem (both in Firefox and in Safari) -- if I go to the above URL, wait for it to load and start running, and then click on the "GREEN" button, the contents of the `container` div changes to "YELLOW papa", and the text is in yellow.  Maybe half a second later, the text changes to green, as the CSS styling is applied.

This only happens the first time you click on the "GREEN" button -- if you then click on the "RED" button and click on "GREEN" again, it seems the necessary files are cached and so there's no flickering.  But if you reload the entire Plunker page, the problem will show up again the next time you click on "GREEN".

I'm not sure that this is a solvable problem -- it may be something to do with the way the browser itself is applying CSS to the page contents.

Oh, I tried forking your Plunker and adding a "resolve", but it seems that your updated version of `angular-ui-router-styles` fixes the problem with the resolve adding to the delay in CSS styling.  So it's better, though the flickering is still very noticeable (I had one of our testers complain about it again this morning).

Finally, no, the states are not nested deeply at all.  Just A -> B, and  then B -> C (two levels deep, max).

Thanks!

 - Erik.

**Comment by manuelmazzuola** [comment]
You are right, I've tested it in Chrome. In Firefox is showing.
I can try to remove the old css files only when the new ones are added and loaded, in this way the problem should be resolved.  Could this be the solution for the problem ?

**Comment by erikwestra** [comment]
Ah, glad you could see the problem.  Ionic apps are built on top of Safari, so that shows the same problem as it shows in Firefox.  Looks like Chrome does a better job of dealing with CSS switches...if only we could do everything in Chrome, but for Ionic apps (on iOS) we're stuck with Safari, unfortunately.

Anyway, your suggestion sounds good.  I could imagine some possible issues if the same CSS selector is used in both files, which might possibly result in the new content having the old CSS styling applied to it -- but that's just a theory.  We really need to see how it works in practice.

Thanks!

 - Erik.

**Comment by manuelmazzuola** [comment]
Could you test this on FF and Safari ? http://plnkr.co/edit/sjSQ266C16Gh5hbCpbRz?p=preview

**Comment by erikwestra** [comment]
Hi Manuel, sorry it took me so long to get back to you.

Yes, this fixes the problem perfectly!

Thank you -- you'll make our testing team very happy indeed.
