### ISSUE TITLE
Css not attaching to view

### ISSUE THREAD

**Issue by aaandrew152** [manuelmazzuola/angular-ui-router-styles#9]
I'm not an experienced Angular User and it is entirely possible I am making a silly mistake. 

Here is my issue: 
I am using angular ui router, and I wish to use angular-ui-router-styles to attach specific css files to specific views. However, the css file is not being called. The ui-router is working  fine, and I receive no error messages in console, moreover when I type an invalid file address into the css section of aboutUs I still do not receive an error message, leading me to believe that the css file is never searched for.

Here is my config:
app.config( function($stateProvider, $urlRouterProvider) {
		$urlRouterProvider.otherwise('/home');
		$stateProvider
				.state('home', {
					url: '/home',
					templateUrl: '../views/home.html'
				})
				.state('aboutUs', {
					url: '/aboutUs',
					templateUrl: '../views/aboutUs.html',
					data: {
						css: '../styles/test.css'
					}
				});
});

I've already injected uiRouterStyles into my module, and called the script.

Thanks for any help you can give!

**Comment by manuelmazzuola** [comment]
Is the `link` element injected into the html ? Open the developers tools on your browser and check it.

**Comment by aaandrew152** [comment]
No its not injected into the html.

**Comment by manuelmazzuola** [comment]
Dunno, try to write a punklr with your code.
In these days I've wrote some tests and they are all green https://travis-ci.org/manuelmazzuola/angular-ui-router-styles

**Comment by antoescu** [comment]
Had the same problem, make sure your ng-app is on the html tag; http://stackoverflow.com/questions/23061958/how-to-use-head-tag-with-angular-directive#23088982

**Comment by aaandrew152** [comment]
That  fixed it, thanks!

**Comment by GeekAbderrahmen** [comment]
How you fixed it ?
